// TODO : Add Copper Bucket when BucketLib is updated

import ovh.paulem.buildscript.*

plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'

	id("com.modrinth.minotaur") version "2.+"
}

version = project.mod_version + "-" + project.minecraft_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url 'https://jitpack.io' }
	maven { url "https://maven.shedaniel.me/" }
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
	maven { url "https://maven.terraformersmc.com/releases/" }
	maven { url "https://maven.architectury.dev/" }
	maven {
		name "paulemReleases"
		url "https://maven.paulem.ovh/releases"
	}
	mavenLocal()
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"simpleores" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

fabricApi {
	configureDataGeneration() {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	/*modApi("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}
	modImplementation("com.terraformersmc:modmenu:${mod_menu_version}")*/
}

processResources {
	def expandProps = [
			"version": version,
			"min_version_range": min_version_range,
			"max_version_range": max_version_range,
	]

	filesMatching(['fabric.mod.json', '*.mixins.json']) {
		expand expandProps
	}
	inputs.properties(expandProps)
}

def version = JavaVersion.values()[project.java_version.toInteger()-1]

tasks.withType(JavaCompile).configureEach {
	it.options.release = version.toString().toInteger()
}

java {
	sourceCompatibility = version
	targetCompatibility = version
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// ------------------------ MODRINTH ------------------------
modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "Boe3chj8"
    versionNumber = project.version.toString()
    versionName = "SimpleOres Refabricated ${project.mod_version}"
    versionType = "alpha"
    changelog = "**This version does not include the copper bucket, as BucketLib has not yet been updated!**\n\n" + NewGithubChangelog.getChangelog()
    uploadFile = tasks.remapJar.archiveFile.get().asFile
    gameVersions = VersionRangeParser.parseVersionRange(min_version_range, max_version_range)
    loaders = ["fabric", "quilt"]

	dependencies {
		required.project "fabric-api"
		required.project "cloth-config"
		optional.project "modmenu"
		optional.project "energized-power"
	}
}