org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

java_version=21

minecraft_version=1.21.6-pre2
yarn_mappings=1.21.6-pre2+build.2
loader_version=0.16.14

fabric_version=0.125.3+1.21.6

mod_version=1.3.4
maven_group=ovh.paulem.simpleores
archives_base_name=simpleores

min_version_range=1.21.6-beta.1
max_version_range=1.21.6

# UPDATE
# cloth_config_version = 18.0.145
# mod_menu_version = 14.0.0-rc.2