org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

java_version=21

minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.14

fabric_version=0.102.0+1.21

mod_version=1.3.2
maven_group=ovh.paulem.simpleores
archives_base_name=simpleores

min_version_range=1.21
max_version_range=1.21.1

cloth_config_version = 15.0.127
bucketlib_version = 1.21-4.1.3.0
mod_menu_version = 11.0.2