org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

maven_group=net.paulem.simpleores

min_version_range=[VERSIONED]
max_version_range=[VERSIONED]

mod.id=simpleores
mod.version=1.5

deps.fabric_loader=0.18.4
deps.fabricloader_version=*

deps.fabric_api=[VERSIONED]
deps.cloth_config = [VERSIONED]
deps.mod_menu = [VERSIONED]
deps.bucketlib = [VERSIONED]

breaks.fabric_api = <0.1
