version_range=~26.3-

deps.minecraft=26.3-snapshot-8
deps.fabric_api=0.157.1+26.3
#deps.midnightlib=1.9.3+26.2-fabric
#deps.mod_menu=21.0.0-alpha.1

#deps.cloth_config=26.2.155
#deps.bucketlib=26.2-5.2.0.1

# CurseForge reçoit automatiquement "26.3-snapshot" (déduit de deps.minecraft).
# Décommenter uniquement si CurseForge nomme la version autrement.
#curseforge_versions=26.3-snapshot