name: 🚀 Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          if-no-files-found: error
          path: dist/

      - name: ⬆️ Upload to Modrinth/CurseForge
        run: ./gradlew publishUnified
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_UPLOAD_TOKEN }}
          GITHUB_EVENT_RAW_PATH: ${{ github.event_path }}
          GITHUB_COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true