name: 🚀 Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: runDatagen
        run: ./gradlew runDatagen

      - name: Gradle Build
        run: ./gradlew build

      - name: ⬆️ Upload to Modrinth/CurseForge
        run: ./gradlew publishUnified
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_UPLOAD_TOKEN }}
          GITHUB_EVENT_RAW_PATH: ${{ github.event_path }}
          GITHUB_COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true